### PR TITLE
[RHOAIENG-11349] - Missing requirements.txt for modelmesh-runtime-ada…

### PR DESCRIPTION
**Pull request by spolti**
…pter component

chore:  Add the requirements.txt file and steps to generate it and correctly configure
        the Konflux build.

### CODE REVIEW

**Review by MohammadiIram — APPROVED** [review]

**Review by israel-hdez — COMMENTED** [review]
For ModelMesh, this may not change often.
But I wonder if there is any way to run this in Konflux, before the build? perhaps there is some intermediate repository on the build?

Otherwise, we will need to remember to update this each time dependencies change (CVE fixing would be the common source of dep updates)

**Comment by spolti** [comment]
@israel-hdez I believe they can configure a new step in the konflux build to do this, but, IMHO, it is still valid to keep it here as reference for future manual task.
But the version pinning is manual for now, unless we agree to hardcode these in the DOckerfile, that is from where it was taken from.
But, we can have another jira to follow-up it later when the builds would be fully migrated to konflux.

**Comment by Jooho** [comment]
The follow-up jira is to solve @israel-hdez question?

**Comment by spolti** [comment]
> The follow-up jira is to solve @israel-hdez question?

the follow-up jira is to automate the requirements.txt generation.

**Comment by israel-hdez** [comment]
I have the idea that it is going to be much better to add the requirements.txt file in odh repository, rather than here. Even better if we can send the patch to upstream.

Also, I think we should avoid using poetry. It should be enough using pip for generating the file.

**Comment by spolti** [comment]
> Even better if we can send the patch to upstream.

Why do you think we need it upstream?

**Comment by spolti** [comment]
>  I think we should avoid using poetry.

I did with poetry because clean requirements.txt does not allow you to set the python version range and with pip, you needed first to install everything before, then do something like this:

```
pip install pip-tools
pip-compile --generate-hashes -o requirements.txt
```

**Comment by spolti** [comment]
Moved to https://github.com/opendatahub-io/modelmesh-runtime-adapter/pull/65

**Pull request closed without merging**
